version: '3'

services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=my-secret-password
      - POSTGRES_USER=my-user
      - POSTGRES_DB=my-db